version: '3.8'
services:
  zookeeper:
    image: wurstmeister/zookeeper:latest
    container_name: financial-fraud-detection-zookeeper-1
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka:latest
    container_name: financial-fraud-detection-kafka-1
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      # Listen on all interfaces INSIDE container
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      # Advertise as localhost for connections from your Mac host
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper

  postgres:
    image: postgres:15
    ports: [ "5432:5432" ]
    environment:
      POSTGRES_USER: fraud
      POSTGRES_PASSWORD: password
      POSTGRES_DB: frauddb

  redis:
    image: redis:latest
    ports: [ "6379:6379" ]

  alertmanager:
    image: prom/alertmanager
    ports: [ "9093:9093" ]
    volumes:
      - ./monitoring/alertmanager.yml:/etc/alertmanager/alertmanager.yml

  prometheus:
    image: prom/prometheus
    ports: [ "9090:9090" ]
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --web.enable-lifecycle
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - alertmanager
    extra_hosts:
      - "host.docker.internal:host-gateway"

  grafana:
    image: grafana/grafana
    ports: [ "3000:3000" ]
    depends_on:
      - prometheus
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./monitoring/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./monitoring/grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./monitoring/grafana/dashboards:/var/lib/grafana/dashboards
    extra_hosts:
      - "host.docker.internal:host-gateway"
